FROM pallet/java:busybox-latest

COPY target/bulk-loader-{{version}}-standalone.jar /opt/deploy/bulk-loader-{{version}}-standalone.jar
COPY env.sh /opt/deploy/env.sh

RUN chmod u+x /opt/deploy/env.sh

ENV GRAPHITE_PREFIX koomus.bulk-loader.
ENV GRAPHITE_PORT 2003

EXPOSE 1234

ENTRYPOINT ["/opt/deploy/env.sh"]
